### ISSUE TITLE
Crosshair in outline layer

### ISSUE THREAD

**Issue by kasbah** [fossasia/pslab-hardware#104]
Hey, it seems there is a crosshair drawn on the outline layer in the lower left side. Here visualized with the [tracespace viewer](https://tracespace.io/view).

![image](https://user-images.githubusercontent.com/206854/64679947-4888eb80-d46c-11e9-8458-a371f8fd3f27.png)

This causes the tracespace viewer not being able to render the board in the realistic mode at all. [On Kitspace](https://kitspace.org/boards/github.com/fossasia/pslab-hardware/) it looks like this:

![image](https://user-images.githubusercontent.com/206854/64680100-a3bade00-d46c-11e9-9811-3ae1447ff3db.png)

**Comment by CloudyPadmal** [comment]
Ah it looks like the origin marking from KiCAD. Let me make a fix :thinking:
