### ISSUE TITLE
Move ESP to frontside

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab-hardware#107]
The ESP chip is the only module on the backside of the device. Please try to decrease the usage of space on the board and move the chip to the front side.

**Comment by CloudyPadmal** [comment]
ESP is about 1/10th of the whole board and even if we managed to bring it to the top, it would not go with the same solder flow as other components as it is a module. Need to evaluate the effort with the outcome we would get from this.

**Comment by CloudyPadmal** [comment]
Current version in use is ESP12. Most of the pins in this module are unused in PSLab. With this reasoning, we can replace ESP12 with ESP01 which will enable us to move the component to top.
![ESPs](https://user-images.githubusercontent.com/14261304/75329911-2b649f80-5889-11ea-917c-a8dadbcbe4e6.jpg)

**Comment by CloudyPadmal** [comment]
Added in #93
