### ISSUE TITLE
Wave Generator: Triangle wave is deformed

### ISSUE THREAD

**Issue by marcnause** [fossasia/pslab-hardware#111]
When I configure the wave generator to output a triangle wave, the wave which is generated is deformed. I checked with the PSLab's oscilloscope and with an external device.

I would expect the wave to look like the wave that is displayed in the app. 

**1623Hz triangle wave**
![Screenshot_20200106-125240_PSLab](https://user-images.githubusercontent.com/11596220/73166363-9e91bf00-40ed-11ea-8caf-5cc04adb7161.png)

![MAP001](https://user-images.githubusercontent.com/11596220/73166529-efa1b300-40ed-11ea-91f1-3685d93d2067.png)

**615 Hz triangle wave**
![Screenshot_20200106-125337_PSLab](https://user-images.githubusercontent.com/11596220/73166571-047e4680-40ee-11ea-95e7-4abf78502177.png)

![MAP002](https://user-images.githubusercontent.com/11596220/73166583-09db9100-40ee-11ea-8f16-e84387593976.png)

**Comment by justinclift** [comment]
Ouch. :frowning_face:

**Comment by 19-pragya** [comment]
can i work on this??

**Comment by marcnause** [comment]
I am pretty sure that this is a software issue in the Android app. I will close this issue and add a comment to https://github.com/fossasia/pslab-android/issues/2100 instead.
