### ISSUE TITLE
Digital inputs are mislabeled on bottom 

### ISSUE THREAD

**Issue by bessman** [fossasia/pslab-hardware#116]
The digital inputs (LA1-4) are mirrored on the bottom of the board. The pin labeled LA1 is actually LA4, LA2 is LA3, LA3 is LA2, and LA4 is LA1.
![](https://i.imgur.com/3yMs9DO.jpg)
![](https://i.imgur.com/4ZMKe5i.jpg)

**Comment by CloudyPadmal** [comment]
This pin set has been removed in the new version to give space for RTC battery. So I guess we can close this issue.
