### ISSUE TITLE
RGB LED not working

### ISSUE THREAD

**Issue by bessman** [fossasia/pslab-hardware#134]
### Problem Description

On the latest prototype, the onboard WS2812B RGB LED does not work.

#### What steps reproduce the problem?

Power the device. The LED should light up, but does not.

#### What is the expected output?

The LED should light up when the PSLab is powered.

**Comment by mariobehling** [comment]
The WS2812B RGB LED has the option to generate any color. It is not only red. If it does not work it is an issue with your specific board.
