### ISSUE TITLE
SYSTEM / STATUS LED

### ISSUE THREAD

**Issue by bessman** [fossasia/pslab-hardware#138]
### Problem Description

On the new prototype, the LED previously labelled SYSTEM is renamed to STATUS. Why? It seems like an unnecessary change that will lead to confusion since old documentation will need to be updated to reflect the new name.

Its location has also been moved next to the backup battery slot. I think the old location next to the MCU is better, since the new location gives the impression that it's a status LED for the backup battery.

**Comment by mariobehling** [comment]
The name change was done by @CloudyPadmal. Could you explain why this was done, please?

@bessman The change of the location was done due to hardware changes. More space was required and the PIN layout had to be changed.

**Comment by bessman** [comment]
If I recall correctly, @RafaelLeeImg thought it would be possible to move the LED closer to the MCU.

But in any case, the position and name of this LED is a minor detail which should not take up significant time or attention. Since we're rather short-handed at the moment, I'm closing this so that it doesn't clog the backlog.

**Comment by CloudyPadmal** [comment]
If I recall correctly, the LED was renamed to `Status` as it shows the status of MCU operations.
