### ISSUE TITLE
Voltage measurement incorrect when powered via USB

### ISSUE THREAD

**Issue by everthu** [fossasia/pslab-hardware#143]
I've different measurement values for a voltage measurement with PSLab by the use of different  USB sources.
If I use a laptop to power the PSLab board, the voltage measurement is too low. While I should measure a voltage of 6v, the actual voltage measured by PSLab is 4.8v. 
When using a regular PC as USB source I'am measuring a correct voltage of 6v.
It seems like that the USB bus power in case of a labtop is low, around 4,5V.
I was assuming that the PSLab board is using internal reference sources to correct for this issue.
Does someone has any idea what is going on?
The used hardware is V5

**Comment by bessman** [comment]
4.5 V is below the required input voltage of the PSLab's voltage regulator (4.75 V). The analog inputs do have internal voltage refs, but if the supply voltage is too low they become inaccurate.

Basically, if the supply voltage is outside spec all bets are off. Nothing we can do about it.
