### ISSUE TITLE
Use kibot to generate diffs

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/pslab-hardware#147]
Instead of terminal based diff images, now `kibot` has an option called 'diff' that generate diff pdfs between schematics and PCBs. (https://github.com/INTI-CMNB/KiBot)

We may use that for reviewing changes.

**Comment by CloudyPadmal** [comment]
~Fixes in #146~

**Comment by bessman** [comment]
Cool!

How does one read the diffs? At a glance, the diff_schematic.pdf looks identical to PSLab.pdf, just in black-and-white.

**Comment by CloudyPadmal** [comment]
Something is not right with the diff configuration in `CI.kibot.yaml`. The PDF should look like this: [diff_schematic.pdf](https://github.com/fossasia/pslab-hardware/files/13053734/diff_schematic.pdf) with red and green stuff

**Comment by CloudyPadmal** [comment]
Now it works! 🚀
