### ISSUE TITLE
Board Temperature

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/pslab-hardware#152]
I just measured board temperature using in-built methods.

| Old Prototype Board - Old Firmware | Old Prototype Board - New Firmware | New Board - New Firmware |
| ---------------------------------- | ---------------------------------- | ----------------------------- |
| <img width="752" alt="OldBoard-OldFirmware" src="https://github.com/fossasia/pslab-hardware/assets/14261304/cc356840-7b72-4934-8363-04d85fedc092"> | <img width="752" alt="Screenshot 2024-06-11 at 12 54 46 PM" src="https://github.com/fossasia/pslab-hardware/assets/14261304/a6e549a0-cda0-428c-a7fd-0a5ebf98c417"> | <img width="752" alt="NewBoard-NewFirmware" src="https://github.com/fossasia/pslab-hardware/assets/14261304/8bded912-3262-42a6-987a-fee848918f90"> |

New board MCU gets up-to 43 Celsius when the old prototype MCU is around 30-32 Celsius.

**Comment by bessman** [comment]
I don't think this is a problem in and of itself; 43 °C is not worrisome in the sense that it might damage anything. But it does indicate greater power consumption.

This may be related to the resettable fuse problem, and means that battery life in stand-alone mode will be shorter than it could be.

**Comment by bessman** [comment]
Any idea what might be causing it?

One thing that's different between the old and new prototype is the addition of the battery indicator LEDs. As noted elsewhere, they are VERY bright. I wonder if they could be the cause of the increased power draw? Would that manifest as greater MCU temperature?

**Comment by CloudyPadmal** [comment]
I'm not sure what could be the cause. 

It looks like the RGB LED is mounted in reverse and may be it is drawing current. I plan to look more into this in this week.

**Comment by CloudyPadmal** [comment]
I rotated the RGB LED and looks like now it does not heat up anymore.

<img width="300" alt="Screenshot 2024-06-14 at 1 46 20 PM" src="https://github.com/fossasia/pslab-hardware/assets/14261304/f95f6569-ff98-4eae-af1c-be8e619888af">

However, the RGB LED does not light up. I'll try to solder a new one and see as they are quite plasticky and highly possible to get damaged due to reworking with hot air.

**Comment by bessman** [comment]
I suppose this also explains why the RGB LED doesn't work on any of the recent prototypes.

**Comment by mariobehling** [comment]
Is this wrong in the schematics?

**Comment by bessman** [comment]
Looks correct to me:
![Screenshot from 2024-06-14 16-05-14](https://github.com/fossasia/pslab-hardware/assets/1999462/9d4a50e3-3d0d-4462-9d54-ada0fedfb1bb)
![Screenshot from 2024-06-14 16-05-01](https://github.com/fossasia/pslab-hardware/assets/1999462/25ab0db6-dcd2-4904-b563-02128905276b)

I wonder how it ended up backwards? :thinking:

**Comment by cweitat** [comment]
@bessman are u able to check the LED to see if it has the +- sides as the intended component? because sometimes the chinese made chips have reversed poles.

**Comment by bessman** [comment]
Will check tonight unless @CloudyPadmal checks first.

**Comment by cweitat** [comment]
One more thing to check. which colour of LED does it happened? White/Green/Blue

**Comment by CloudyPadmal** [comment]
This notch in the LED should face towards the MCU. It was like that in the early prototype Rafael sent over to us.

| 3D render | Rafael Prototype |
| --------- | ---------------- |
| <img width="300" alt="Screenshot 2024-06-14 at 8 30 20 PM" src="https://github.com/fossasia/pslab-hardware/assets/14261304/eb8ca588-6b78-420d-b8f6-0cc7b85d394c"> | <img width="434" alt="Screenshot 2024-06-14 at 8 30 20 PM" src="https://github.com/fossasia/pslab-hardware/assets/14261304/274df584-2403-42d6-be11-36072baf351b"> |

But this is not the case with the new boards and somehow the LED is rotated. I just checked the `position` file and the rotation is 0 degrees as expected (D5 - Line 52).

Since this rotation causes the `VCC` and `GND` pins to swap, it might have fried the LED in the first place. Let me double check with a new WS2182B LED.

<img width="300" alt="Screenshot 2024-06-14 at 8 46 55 PM" src="https://github.com/fossasia/pslab-hardware/assets/14261304/ddee87d2-7e30-4072-b088-ce7515105f97">

**Comment by bessman** [comment]
> One more thing to check. which colour of LED does it happened? White/Green/Blue

It's the RGB LED. It can be any color. It should be purple in bootloader, green in application.

> @bessman are u able to check the LED to see if it has the +- sides as the intended component? because sometimes the chinese made chips have reversed poles.

It's the same as in the datasheet:
![Screenshot from 2024-06-14 16-05-14](https://github.com/fossasia/pslab-hardware/assets/1999462/9d4a50e3-3d0d-4462-9d54-ada0fedfb1bb)

Previous prototype (correct orientation):
![image](https://github.com/fossasia/pslab-hardware/assets/1999462/33511627-0fed-42cc-91a0-c5337cd264ac)

Current prototype (wrong orientation):
![image](https://github.com/fossasia/pslab-hardware/assets/1999462/d8c815ec-6718-4022-b835-99cb3541810f)

Comparison between previous and current prototypes with board traces marked in yellow and LED pins marked in red:
![20240614_201328](https://github.com/fossasia/pslab-hardware/assets/1999462/b97ec2a2-247d-456d-9199-e51b14daaeab)
![20240614_201415](https://github.com/fossasia/pslab-hardware/assets/1999462/8a420f4a-6bd1-41dc-a565-be3ed41a8945)

**Comment by CloudyPadmal** [comment]
Looks like the model got protection against reverse connections.

<img width="500" alt="Screenshot 2024-06-14 at 8 57 04 PM" src="https://github.com/fossasia/pslab-hardware/assets/14261304/8b89b279-09bf-4f19-be6e-2609dfb5d8e6">

**Comment by cweitat** [comment]
What can we conclude from here? That the GERBER wasn't followed in regards to the LED direction and because of this, it resulted in faults of ____?

**Comment by CloudyPadmal** [comment]
> What can we conclude from here? That the GERBER wasn't followed in regards to the LED direction and because of this, it resulted in faults of ____?

I will finalize this by tomorrow or the day after at the latest.

**Comment by CloudyPadmal** [comment]
So I was able to test again.

The RGB LED was burnt and I replaced it with a spare one and now it lights up.

<img src="https://github.com/fossasia/pslab-hardware/assets/14261304/af26f5e7-7eb9-409a-a501-2484e0e581cb" width=500 />

I did a temperature test, and it seems normal with the new RGB LED.
<img width="500" alt="tmp" src="https://github.com/fossasia/pslab-hardware/assets/14261304/1d555233-5e5c-4680-a705-329206485859">


Now the conclusion is that, 

- The RGB LED (D5) requires manual de-soldering to correct its position.
- [`PositionFile.csv`](https://github.com/fossasia/pslab-hardware/blob/pslab-v6/docs/position_files/PositionFile.csv) is still correct. I'm not sure why the LED was rotated during assembly.
- I suspect that the fuse was protecting the board from this LED creating a short. Therefore, we will pause the fix we had earlier (shorting the fuse) until a fresh board is tested with the LED in the correct position.

**Comment by cweitat** [comment]
I had a chat with the manufacturer side and they want to clarify few items:
![bf6dc1860bb889e78b76800b8d90abb](https://github.com/fossasia/pslab-hardware/assets/11439477/d89013c7-81d8-49e2-be30-79ccd2d89b49)
does the yellow circle meant the direction of placement/polarity for the component?

More example of the schematics
|  |  |  |
|--------|--------|--------|
| ![305239b96e6b1eee908c50445a4f095](https://github.com/fossasia/pslab-hardware/assets/11439477/03d967a9-e109-4d29-9f75-a95a0a0f0c36)| ![0d297eb0522aa5f91c7341b5d41fae5](https://github.com/fossasia/pslab-hardware/assets/11439477/200669ba-310d-4086-9cb8-04790c3d0d89)| ![e742145b6ff826ac330d29b478a79f8](https://github.com/fossasia/pslab-hardware/assets/11439477/1694a64a-9c98-47a4-a04e-12649d98d61f)|
| ![cea5623be75f060a064681fa1328cee](https://github.com/fossasia/pslab-hardware/assets/11439477/63153c0a-83c1-4cc1-b0e7-e3c7c45de297)| ![f14772f8f5351ea6953a584abbc6562](https://github.com/fossasia/pslab-hardware/assets/11439477/83491cae-e69d-4431-9815-6004aff381dc)| |

**Comment by CloudyPadmal** [comment]
The yellow circle marks the pin 1 in an IC or a component. Also on the silk screen, a special marking shows where a special marking of an IC or a component should align.

![340600617-d89013c7-81d8-49e2-be30-79ccd2d89b49](https://github.com/fossasia/pslab-hardware/assets/14261304/5c12caf4-f9e4-4f62-a92e-33c7b491d066)

In this figure I have marked such markings for the MCU and the RGB LED.

**Comment by CloudyPadmal** [comment]
The standard is that this special marking is next to pin 1. Apparently for WS2812B RGB LED, the special marking is next to pin 3. Maybe this is where it went off-road for the manufacturer.

![WS2812B-Neopixel-LED-Pinout-pico](https://github.com/fossasia/pslab-hardware/assets/14261304/b115b91a-1cbd-4f2a-8685-2753fe4216e9)

**Comment by CloudyPadmal** [comment]
## Conclusion

The recently manufactured and assembled boards have an issue.

The issue is that the RGB LED (WS2182B) (D5) is mounted incorrectly, with the VCC (pin 1) and GND (pin 3) swapped. This creates a type of short circuit, rendering the board unusable unless the LED is manually removed and repositioned correctly according to the parameters in the provided PositionFile.csv.

It appears that the manufacturer missed the visual inspection step to verify that the IC pin markings align with the silk screen markings. This issue was caused by the manufacturer’s fault, as all the specifications and files we provided were correct.

@mariobehling @cweitat

**Comment by cweitat** [comment]
@CloudyPadmal only Gerber,  BOM & pick and place zip file from the build was given to the manufactuerer. Is the positionfile.csv is in any of the zip folders?

**Comment by CloudyPadmal** [comment]
@cweitat `Pick and Place` and `Position` are the same file, with different names.

**Comment by cweitat** [comment]
Reply from them: Pick and Place procedure is not able to verify the direction of the components, only the positioning.

**Comment by CloudyPadmal** [comment]
Yes, and they got it wrong as it does not require a rotation (0 degrees)

Edit: in fact, pick and place says about rotation. Otherwise cannot get all the other ICs in right orientation.

**Comment by cweitat** [comment]
They followed the yellow dots as provided in the file as the standard practice as they did with their other customers. And it also impossible to see whether the direction was wrong with just look of it. Moreover, this was only highlighted more than 2 months after it was shipped out

**Comment by bessman** [comment]
> They followed the yellow dots as provided in the file as the standard practice

They did not; standard practice is that the yellow dot marks the connection point for pin 1. They have connected pin 3 at the yellow dot.

> it also impossible to see whether the direction was wrong with just look of it.

Incorrect. There are at least two ways to confirm correct orientation with visual inspection:

1. Note the location of the triangular marking next to pin 3, as specified in the datasheet
2. Ensure that the LED actually turns on when powered (as I believe we instructed them to do?)

**Comment by cweitat** [comment]
@bessman Yes. The file given them had the error of  yellow dot placed at pin 3, not pin 1, which is what Padmal brought up [earlier messages.](https://github.com/fossasia/pslab-hardware/issues/152#issuecomment-2176158741) So in this case, meaning the Gerber was wrong and they just followed in accordance to the file given. 

Their scope is not to look through the schematics and all components datasheet to give feedback because the service engaged was just manufacturing and assembly.

There was no mention of how testing should be done other than LED lighting up. It was raised prior to the production and only the lighting up of LED was mentioned.

For point 2, yes the test was plug in power and see if the LED lights up. No particular instructions was mentioned as to which LED lights up etc. Also, there's no manual for test as well, other than an old one. In this case, the white LED lights up so it's considered as a pass.

**Comment by CloudyPadmal** [comment]
> @bessman Yes. The file given them had the error of  yellow dot placed at pin 3, not pin 1, which is what Padmal brought up [earlier messages.](https://github.com/fossasia/pslab-hardware/issues/152#issuecomment-2176158741) So in this case, meaning the Gerber was wrong and they just followed in accordance to the file given. 

I didn't say that the files we provided including the Gerber and pick and place was wrong. They are 100% correct and the manufacturer went in their own way to decide the orientation. 

I just mentioned that the RGB LED doesn't have the pin marking in pin 1 unlike other ICs and it has the marking on pin 3 instead.

My bad for putting out too much information...

**Comment by CloudyPadmal** [comment]
I don't know how else to say that it was the manufacturer who messed up the assembly which took us some time to debug 🙆🏻‍♂️

Please don't misinterpret and the production files are still valid and 100% correct.

**Comment by CloudyPadmal** [comment]
> And it also impossible to see whether the direction was wrong with just look of it. 

Just looking at it is in fact the visual inspection stage where you identify ICs assembled in wrong orientations. Check my previous comments about silk screen markings. 

This is the standard procedure with PCBWay and JLCPCB.

![image](https://github.com/fossasia/pslab-hardware/assets/14261304/d4d036ee-da2a-4ebc-9d75-95bd4844adf4)

**Comment by cweitat** [comment]
AOI machine file for polarity testing comes from the provided Gerber (which had the dot on pin 3) as well. So the test would have passed any ways.

**Comment by CloudyPadmal** [comment]
Dot is in pin 1 as mentioned earlier. 

I'm repeating the same thing and I don't think this discussion yields anything.

**Comment by cweitat** [comment]
@CloudyPadmal yes I understand that as well. Therefore I left the communication to the manufacturer with Mario now.

**Comment by CloudyPadmal** [comment]
Sounds good. I'm closing this issue as now we know that the manufacturer did not follow the design files correctly and we will manually fix the LEDs with their supposed orientation before shipping out to customers.
