### ISSUE TITLE
Libraries not found in the .pro files

### ISSUE THREAD

**Issue by sudheesh001** [fossasia/pslab-hardware#3]
The error message received is as follows:

![kicad libraries](https://cloud.githubusercontent.com/assets/4545925/24602287/c74f0a28-1879-11e7-9e91-7168433551cd.PNG)

**Comment by jithinbp** [comment]
Hi,

Sorry about that. i did not notice the shared libraries. Will upload by
tonight.
In the meantime you could try skipping the error, and it might pick up the
cached library

**Comment by jithinbp** [comment]
please check the latest pull request. Added proto1.lib 
I see the same errors, but I can simply skip it, and the schematic picks up the files from proto1-cache.lib . Can you check?
![kicad_missing](https://cloud.githubusercontent.com/assets/6078658/24621073/d514e044-18bd-11e7-90b3-a165aa22fa60.png)

**Comment by wavicles** [comment]
Closed with #4
