### ISSUE TITLE
Rethink usage of Tantalum capacitors

### ISSUE THREAD

**Issue by gallioleo** [fossasia/pslab-hardware#69]
From the ethical point of view are tantalum capacitors critical, cause tantalum is a conflict mineral - see link below. Another point are the cost of this capacitor. If the project doesn't need the high capacitance with small geometrical size, you should think about the phase out of these caps.

https://www.electronicdesign.com/blog/conflict-minerals-and-tantalum-capacitor-supply-chain

**Comment by cweitat** [comment]
@gallioleo according to KiCad, we are using KEMET but we are using Samsung capacitors during production. So not much problems with that. We will still take your view into consideration. Thanks :)

http://images.samsung.com/is/content/samsung/p5/pl/aboutsamsung/2017/pdf/About-us-sustainability-report-and-policy-confilct-mineral-policy-en.pdf

http://www.samsungsem.com/global/product/passive-component/tantalum1/index.jsp
